spring:
  #数据库链接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/com_net
    username: root
    password: 123456
  #文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


  #获取静态文件
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/templates/
        - classpath:/public/


# 输出日志  驼峰命名
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


# spring 事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbctransactionManager: debug

server:
  port: 5678

# 配置PageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# mybatis_plus配置
mybatis-plus:
  mapper-locations: classpath:/mappers/**/*xml
  type-aliases-package: com.zaizi.pojo

# 文件上传地址
file:
  upload-dir: E:/Desktop/ComNetCur/backend/src/main/resources/static/
  serve-dir: http://127.0.0.1:5678/
